# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane




default_platform(:ios)
platform :ios do
  before_all do
    FASTLANE_USER = ENV["ruchiraj1604@gmail.com"]
     key_id = ENV["QYDCJL583Z"],
     issuer_id = ENV["69a6de90-b48c-47e3-e053-5b8c7c11a4d1"],
     key_content = ENV["LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ1RFWmJRNUZYQ3lIWFFGSDAKT295a2YwVjI5VVRIeU9XVitkdFF2cENySUs2Z0NnWUlLb1pJemowREFRZWhSQU5DQUFUenhueER6WEV6M0JtcQovYkFlNngyTTU1MGY4azR5UU91M0syMnJmNDdrZlYrWlFaSTU5OThPcUNxM2JheHh2eGVaRCszSER5bkkyQ0J4CjRkNWg1Q25PCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0"]
  end

 desc "Load ASC API Key information to use in subsequent lanes"
 lane :load_asc_api_key do
  puts "Inside the ENvs"
   app_store_connect_api_key(
     key_id: ENV["QYDCJL583Z"],
     issuer_id: ENV["69a6de90-b48c-47e3-e053-5b8c7c11a4d1"],
     key_content: ENV["LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ1RFWmJRNUZYQ3lIWFFGSDAKT295a2YwVjI5VVRIeU9XVitkdFF2cENySUs2Z0NnWUlLb1pJemowREFRZWhSQU5DQUFUenhueER6WEV6M0JtcQovYkFlNngyTTU1MGY4azR5UU91M0syMnJmNDdrZlYrWlFaSTU5OThPcUNxM2JheHh2eGVaRCszSER5bkkyQ0J4CjRkNWg1Q25PCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0"],
     is_key_content_base64: true,
     in_house: false # detecting this via ASC private key not currently supported
   )
 end

 desc "Sync certificates"
 lane :sync_certificates do
   #read-only disables match from overriding the existing certificates.
   match({readonly: true, type: "adhoc"})
 end

desc "Create ipa"
 lane :build do
   increment_build_number
   gym
 end

desc "Upload to TestFlight"
 lane :beta do
   build  
   pilot
  end
  
end
