# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane




default_platform(:ios)
platform :ios do

 desc "Sync certificates"
 lane :sync_certificates do
   #read-only disables match from overriding the existing certificates.
   match({readonly: true, type: "adhoc"})
 end

desc "Increment the Build"
 lane :build do
  puts "Inside the Build incrementer"
  version_number = get_version_number(target: "KidsLearning (iOS)")
    latest_build_number = get_latest_testflight_build_number(version_number: version_number)
    build_number = latest_build_number + 1
    increment_build_number(
      build_number: build_number
    )
   increment_build_number
   gym
 end

desc "Upload to TestFlight"
 lane :beta do
   build  
   pilot
  end
  
end
